export enum Keyword {
  Alter = "alter",
  Begin = "begin",
  Call = "call",
  Comment = "comment",
  Commit = "commit",
  Create = "create",
  Declare = "declare",
  Delete = "delete",
  Delimiter = "delimiter",
  Drop = "drop",
  Else = "else",
  End = "end",
  Flush = "flush",
  From = "from",
  Grant = "grant",
  Having = "having",
  If = "if",
  Insert = "insert",
  Join = "join",
  Leave = "leave",
  Limit = "limit",
  Rename = "rename",
  Replace = "replace",
  Return = "return",
  Select = "select",
  Set = "set",
  Show = "show",
  To = "to",
  Truncate = "truncate",
  Update = "update",
  Use = "use",
  Where = "where",

  CommentHash = "#",
  CommentDash = "--",
  CommentMultiLineStart = "/*",
  CommentMultiLineEnd = "*/",

  Newline = "\n",
  WindowsNewline = "\r\n",
}
