export enum Keyword {
  Alter = "alter",
  Begin = "begin",
  Call = "call",
  Create = "create",
  Declare = "declare",
  Delete = "delete",
  Drop = "drop",
  Else = "else",
  From = "from",
  Having = "having",
  If = "if",
  Insert = "insert",
  Join = "join",
  Leave = "leave",
  Limit = "limit",
  Replace = "replace",
  Return = "return",
  Select = "select",
  Set = "set",
  Show = "show",
  Truncate = "truncate",
  Update = "update",
  Use = "use",
  Where = "where",
}
